### ISSUE TITLE
Intellij 2022.2.1 released and now it is not compatible

### ISSUE THREAD

**Issue by johntibagan** [bancolombia/scaffold-ca-intellij-plugin#20]
![image](https://user-images.githubusercontent.com/32622920/186544802-75ae3f4f-9227-4a9a-a4fb-ac7e76290e9b.png)

![image](https://user-images.githubusercontent.com/32622920/186544844-220967f2-e459-44f2-bcee-7ccd450141dd.png)

**Comment by jakspok** [comment]
Hello, how are you, could you update your development ide since we have a new version that is fully compatible 
![image](https://user-images.githubusercontent.com/35540121/193860315-a32bede1-9415-428b-ba96-b473c3726642.png)

**Comment by jakspok** [comment]
Hi, @johntibagan you cant try con this version 
<img width="506" alt="image" src="https://user-images.githubusercontent.com/35540121/194886145-74e28eda-5fa1-4397-9b5f-273d10f4798a.png">
