### ISSUE TITLE
Not compatible version Intellij 2022.2.2 Ultimate Edition

### ISSUE THREAD

**Issue by AlejandroBalseca** [bancolombia/scaffold-ca-intellij-plugin#23]
Hi everyone,
Im using the latest version of Intellij Ultimate Edition in this moment (Build #IU-222.4167.29) and It show a error message:
"is not compatible with the current version of the IDE"

![Error](https://user-images.githubusercontent.com/108755604/193936098-6240fc8b-3371-4c7c-82d1-99394c0d6111.png)

**Comment by jakspok** [comment]
Hi, @AlejandroBalseca you cant try con this version 
<img width="506" alt="image" src="https://user-images.githubusercontent.com/35540121/194886145-74e28eda-5fa1-4397-9b5f-273d10f4798a.png">
